### ISSUE TITLE
Roadmap to Version 2.0.0

### ISSUE THREAD

**Issue by pixelass** [sinnerschrader/dekk#103]
- [ ] Rewrite Dekk
- [ ] Use React Context API
- [ ] React 17+
- [ ] Use emotion.js
- [ ] use memo
- [ ] use functional components
- [ ] provide hooks for common operations
- [ ] use framer-motion for animations
- [ ] ensure SSR compatibility
- [ ] Rethink Master slides
- [ ] Rethink Fragments and Sequences
- [ ] Take Accessibility VERY SERIOUS
- [ ] Rewrite Presenter View
- [ ] Better plugin API
- [ ] Add interaction API
- [ ] Better streaming API
- [ ] Optimize for performance
- [ ] Better mobile / responsive support
- [ ] Rethink core vs community packages
